#@ load("@ytt:data", "data")
#@ load("workflows.lib.yml", "pull_request_defaults")

#@ def branches():
#@ if hasattr(data.values,"workflows_check"):
#@ return pull_request_defaults(data.values.workflows_check)
#@ else:
#@ return pull_request_defaults()
#@ end
#@ end

name: workflows check

"on": #@ branches()
jobs:
  check_workflows:
    name: check-workflows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "^1.14.4"
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.GFLOWS_SSH_READONLY }}
    - uses: jbrunton/setup-gflows@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: validate workflows
      env:
        GFLOWS_CONFIG: .gflows/config.yml
      run: gflows check
